default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.dig(:db, :username) || 'postgres' %>
  password: <%= Rails.application.credentials.dig(:db, :password) || 'password' %>
  host: db

development:
  <<: *default
  database: accuweather_development

test:
  <<: *default
  database: accuweather_test

production:
  <<: *default
  database: accuweather_production
